[package]
name = "sticker"
version = "0.1.0"
edition = "2018"
authors = ["DaniÃ«l de Kok <me@danieldk.eu>"]

[dependencies]
conllx = "0.11"
failure = "0.1"
finalfusion = "0.5"
ndarray = "0.12"
protobuf = "1"
serde = "1"
serde_derive = "1"
tf-proto = { git = "https://github.com/danieldk/tf-proto-rs", tag = "v1.4.0" }
tensorflow = "0.13"

[dev-dependencies]
approx = "0.3"
